def viterbi(observations, states, start_p, trans_p, emit_p):
    """
    An altered version of the viterbi algorithm that takes a probability distribution for each step 
    instead of for each state. This allows for the viterbi algorithm to be performed with the prior probabilities
    generated by a classification algorithm that is run indepentantly for each step. 
    
    Source: https://en.wikipedia.org/wiki/Viterbi_algorithm
    :param observations:
    :param states:
    :param start_p:
    :param trans_p:
    :param emit_p:
    :return:
    """
    V = [{}]
    for st in states:
        V[0][st] = {"prob": start_p[st] * emit_p[st][observations[0]], "prev": None}

    # Run Viterbi when t > 0
    for t in range(1, len(observations)):
        V.append({})
        for st in states:
            max_tr_prob = V[t - 1][states[0]]["prob"] * trans_p[states[0]][st]
            prev_st_selected = states[0]
            for prev_st in states[1:]:
                tr_prob = V[t - 1][prev_st]["prob"] * trans_p[prev_st][st]
                if tr_prob > max_tr_prob:
                    max_tr_prob = tr_prob
                    prev_st_selected = prev_st

            max_prob = max_tr_prob * emit_p[st][observations[t]]
            V[t][st] = {"prob": max_prob, "prev": prev_st_selected}

    # for line in dptable(V):
    #     print(line)

    opt = []
    max_prob = 0.0
    best_st = None
    # Get most probable state and its backtrack
    for st, data in V[-1].items():
        if data["prob"] > max_prob:
            max_prob = data["prob"]
            best_st = st
    opt.append(best_st)
    previous = best_st

    # Follow the backtrack till the first observation
    for t in range(len(V) - 2, -1, -1):
        opt.insert(0, V[t + 1][previous]["prev"])
        previous = V[t + 1][previous]["prev"]

    print("The steps of states are " + " ".join(opt) + " with highest probability of %s" % max_prob)


# def dptable(V):
#     # Print a table of steps from dictionary
#     yield " " * 5 + "     ".join(("%3d" % i) for i in range(len(V)))
#     for state in V[0]:
#         yield "%.7s: " % state + " ".join("%.7s" % ("%lf" % v[state]["prob"]) for v in V)


observations = ("normal", "cold", "dizzy")
hidden_states = ("Healthy", "Fever")
start_probs = {"Healthy": 0.6, "Fever": 0.4}
trans_probs = {
    "Healthy": {"Healthy": 0.7, "Fever": 0.3},
    "Fever": {"Healthy": 0.4, "Fever": 0.6},
}
emit_probs = {
    "Healthy": {"normal": 0.5, "cold": 0.4, "dizzy": 0.1},
    "Fever": {"normal": 0.1, "cold": 0.3, "dizzy": 0.6},
}

viterbi(observations, hidden_states, start_probs, trans_probs, emit_probs)
